name: vault
namespace: vault
source:
  repoURL: https://helm.releases.hashicorp.com
  targetRevision: 0.28.1
  chart: vault
# ignoreDifferences:
#   - group: admissionregistration.k8s.io
#     kind: MutatingWebhookConfiguration
#     jqPathExpressions:
#       - .webhooks[]?.clientConfig.caBundle

# values_source:
#   repoURL: https://github.com/imtpot/argocd-demo.git
#   targetRevision: vault
#   path: argocd/infrastructure/production/vault/values.yaml

# extra_source:
#   repoURL: https://github.com/imtpot/argocd-demo.git
#   targetRevision: vault
#   path: argocd/infrastructure/production/vault/extra/
