name: vault
namespace: vault
source:
  repoURL: https://helm.releases.hashicorp.com
  targetRevision: 0.28.1
  chart: vault

ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
      - .webhooks[]?.clientConfig.caBundle

values:
  injector:
    enabled: false
